name: Build & Push both services to ACR (monorepo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "users-api/**"
      - "products-api/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: users-api
            context: users-api
            image: users-api
          - service: products-api
            context: products-api
            image: products-api

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔐 Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔑 Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🏷️ Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # 🔍 Paso de debug (temporal)
      - name: Debug matrix vars
        run: |
          echo "service=${{ matrix.service }}"
          echo "context=${{ matrix.context }}"
          echo "image=${{ matrix.image }}"
          ls -la
          ls -la "${{ matrix.context }}"

      # Opción A: build manual (si prefieres quedarte con docker CLI)
      - name: 🏗️ Build & Push ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest "${{ matrix.context }}"
          docker tag  ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}

      # --- O ---
      # Opción B (recomendada): buildx action (comenta la opción A si usas esta)
      # - name: 🏗️ Build & Push ${{ matrix.service }} (buildx)
      #   uses: docker/build-push-action@v5
      #   with:
