name: Build & Push both services to ACR (monorepo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "users-api/**"
      - "products-api/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: users-api
            context: users-api
            image: users-api
          - service: products-api
            context: products-api
            image: products-api

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔐 Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔑 Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🏷️ Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: 🏗️ Build & Push ${{ matrix.service }}
        # build from the service folder to guarantee a valid context
        working-directory: ${{ matrix.context }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "Building service: ${{ matrix.service }}"
          echo "Context dir: ${{ matrix.context }}"
          echo "Image: ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest"
          # build from current directory (the service folder) so there's always a context
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest .
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}
          