name: 🚀 Build and Deploy to ACR

on:
  push:
    branches:
      - main

env:
  REGISTRY: yourregistry.azurecr.io
  IMAGE_NAME: your-image-name

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: users-api
            context: .
          # Puedes agregar más servicios si los tienes:
          # - service: orders-api
          #   context: ./orders-api

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 🏷️ Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: 🧩 Debug: verify Docker context
        run: |
          echo "Building service: ${{ matrix.service }}"
          echo "Context directory: ${{ matrix.context }}"
          ls -la "${{ matrix.context }}"

      - name: 🐳 Build & Push ${{ matrix.service }} to ACR
        run: |
          echo "Starting Docker Buildx..."
          docker buildx create --use --name multiarchebuilder || docker buildx use multiarchebuilder
          docker buildx inspect --bootstrap

          echo "Building and pushing image..."
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ matrix.service }}:${{ env.TAG }} \
            -t ${{ env.REGISTRY }}/${{ matrix.service }}:latest \
            ${{ matrix.context }} \
            --push
